### ISSUE TITLE
Does pippo support cookie?

### ISSUE THREAD

**Issue by jerryisbusy** [pippo-java/pippo#416]
I'm tring to build a web application with Pippo.
But i don't find cookie support from documentation.
Does it support cookie?

**Comment by decebals** [comment]
Pippo comes with a good support for cookie. See cookie methods from [Request](https://github.com/pippo-java/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/Request.java#L604) and [Response](https://github.com/pippo-java/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/Response.java#L161).
You can access the `Request` and `Response` from a `RouteContext` object via `routeContext.getRequest()` and `routeContext.getResponse()`.

**Comment by jerryisbusy** [comment]
Perfect!
