### ISSUE TITLE
Update to Freemarker 2.3.28

### ISSUE THREAD

**Issue by mhagnumdw** [pippo-java/pippo#421]
I want to use the auto-escape feature available from least version 2.3.24 of Freemarker.

I've already made changes in my Pippo repo (1.9.0-SNAPSHOT) updating to Freemarker 2.3.23 (current) to 2.3.28 (latest) and my application behaved as expected (no errors) on all screens.

Can I make a pull request? Or do I need to go into more detail here?

**Comment by decebals** [comment]
Please submit a PR.

**Comment by mhagnumdw** [comment]
Is SNAPSHOT up to date?

When should the next release come out?

**Comment by decebals** [comment]
@mhagnumdw
> Is SNAPSHOT up to date?

Yes.

> When should the next release come out?

I wish to include #420 in the next release. Can you take a look please?

**Comment by mhagnumdw** [comment]
@decebals 

I took a look. I will comment there.
