### ISSUE TITLE
routeContext.getParameter("parameter").toString() not returning data when application is deployed as war

### ISSUE THREAD

**Issue by yanvir** [pippo-java/pippo#426]
Hi decebals,

I'm new in using pippo, and pippo is very helping me when creating API. Right now, I already created API using pippo and succeeded when I use embedded web server (jetty), but then I have an issue when I create the API to war and deploy it on tomcat / jetty (as independent web server) .

All the parameter that can work when I'm use it with embedded server suddenly can't be accessed to be passed to the local String variable, when I use `routeContext.getParameter("parameter").toString()` the result always _null_

Is there any other setting that I have to change when I compile the application to war?

**Comment by decebals** [comment]
We are happy to have new users in our community. We will check and we will come with a response.

**Comment by yanvir** [comment]
[I still have the problem now, I have tried my code using multiple server (tomcat, jetty, wildfly), when the application is compiled to war, I can access the API but every parameter posted to the API, I always get null as the result. Even when I use simple code like this:

```
package com.bbw;
import javax.servlet.http.HttpServletRequest;
import org.eclipse.jetty.client.HttpRequest;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import ro.pippo.core.Application;
import ro.pippo.core.ParamField;
import ro.pippo.core.ParameterValue;
public class PippoApplication extends Application {
    private final static Logger log = LoggerFactory.getLogger(PippoApplication.class);
    @Override
    protected void onInit() {
        getRouter().ignorePaths("/favicon.ico");        	
        	POST("/test", routeContext -> {        	
        		String phone		= routeContext.getParameter("phone").toString();
        		System.out.println(phone);
         routeContext.json().negotiateContentType().send("{\"test\":\"" + phone + "\"}");
        });
```
the return will always like this:

![screenshot_24](https://user-images.githubusercontent.com/15225292/40222049-6c12bd68-5aa8-11e8-9683-c72bc81a3cfe.jpg)

I'm stuck with this matter because there's no workaround I can find in the internet, please help me @decebals . Thanks for your attention

**Comment by decebals** [comment]
Today you will have a resolution for this idem.
Related to war, pippo and tomcat, I use [this](https://gist.github.com/decebals/9f7e57e42b705be8a092) technique to test war in tomcat.
Do you see something strange (errors, ...) in log?

**Comment by yanvir** [comment]
I followed the link you shared with me, though I'm not build the shell, but I follow the step you wrote on that script.
I didn't find any strange errors or log from wildfly (the last server I test the code) when I make request to the API, you can see the log created below:

> 14:02:47,610 INFO  [org.jboss.as.server] (External Management Request Threads -- 2) WFLYSRV0016: Replaced deployment "testapi.war" with deployment "testapi.war"
> 14:02:47,614 INFO  [org.jboss.as.repository] (External Management Request Threads -- 2) WFLYDR0002: Content removed from location D:\Project\wildfly\standalone\data\content\04\bd3ec92bbebf3318da66257a9c8d23fca41c25\content
> 14:03:04,819 INFO  [ro.pippo.core.PippoFilter] (default task-2)
>  ____  ____  ____  ____  _____
> (  _ \(_  _)(  _ \(  _ \(  _  )
>  ) __/ _)(_  ) __/ ) __/ )(_)(   http://pippo.ro
> (__)  (____)(__)  (__)  (_____)  1.5.0
> 
> 14:03:04,829 INFO  [ro.pippo.core.Languages] (default task-2) Using 'en' as default language.
> 14:03:04,896 INFO  [ro.pippo.core.PippoFilter] (default task-2) Pippo started (PROD)
> 14:03:04,905 INFO  [stdout] (default task-2) null


FYI, I build the project structure from  http://www.pippo.ro/dev/quickstart.html and just changes few line of code and deployed it on the web servers I mentioned before, and all resulted the same when request parameter: null

**Comment by decebals** [comment]
I cannot reproduce the problem.
I used https://github.com/decebals/pippo-test with following modifications:
- add test route in `PippoApplication`
```java
// #426
POST("/test", routeContext -> {
    String phone = routeContext.getParameter("phone").toString();
    System.out.println(phone);
    routeContext.json().negotiateContentType().send("{\"test\":\"" + phone + "\"}");
});
```
- install Apache Tomcat 7.0.57 in ./`apache-tomcat-7.0.57 ` directory
- run tomcat via `./run-tomcat.sh` script
- simulate POST request with `curl -d "phone=1234567" -X POST http://localhost:8080/test`

The result:
![image](https://user-images.githubusercontent.com/1248311/40251746-e1d1f96c-5ae2-11e8-9181-c8cfb4159953.png)

```
curl -d "phone=1234567" -X POST http://localhost:8080/test
{"test":"1234567"}
```

**Comment by yanvir** [comment]
Thanks for your step-by-step explanation on how you test the application, I follow those procedures and can get the same result with the API, however, when I change the Tomcat setting to bind with an ip, the result can be different when the API is consumed via postman or using curl.

When I accessed using postman and request the same API the request parameter result always shows null value, but when I use curl from the same server, the API will show the value result, here I enclose the screenshot from the result:

![screenshot_29](https://user-images.githubusercontent.com/15225292/40271190-1a10c5ce-5bc4-11e8-8031-dd01021d2397.jpg)

I guess this is about tomcat configuration, do you have any suggestion regarding tomcat's setting that I should change when I bind the tomcat to an ip?

**Comment by decebals** [comment]
My first intention was to test like you, with Postman, but I prefer to use (always when I can) a most low level tool so I chosen curl.
From what you say, I understand that with curl everything works OK and with Postman you encounter problems. Correct?

**Comment by yanvir** [comment]
I may miss an information to you, when I use postman, I access the API from another computer, so not because of the application that access the API itself.

When I make a request to the API from another computer, the API will return 'null' for parameter phone., but when I make a request to the API from the same computer where the API deployed, the API will return the value of the parameter.

**Comment by decebals** [comment]
This is what I meant. When you test a functionality it's important to use a low level approach (curl in our case), to isolate the problem from the environment (Apache or Nginx proxy, tomcat configuration, ...).
So, in my opinion, the problem is not related to Pippo.
One idea is to simplify the test and use a simple servlet war instead of Pippo, to see if you retrieve the same issue.

**Comment by yanvir** [comment]
I follow your suggestion and I use curl to test, but then I found out that what the command you use for curl might not right, I tried this command and the API still return null:

`curl -X POST -F "phone=12345" http://localhost:8080/test`
result: {"test":"null"}

**Comment by decebals** [comment]
Take an [example](https://gist.github.com/subfuzion/08c5d85437d5d4f00e58#post-applicationx-www-form-urlencoded).
Also take a look at https://superuser.com/a/1254742

> This will be POST-ed as `application/x-www-form-urlencoded` (used for the majority of forms that don't contain file uploads):
> 
> ```java
> curl http://httpbin.org/post \
>     -H "User-Agent: Mozilla/2.2" \
>     -d param1=hello \
>     -d name=dinsdale
>```
>
> For a `multipart/form-data POST` use `-F` (typically used with forms that contain file uploads, or where order of fields is important, or where multiple fields with the same name are required):
> 
> ```java
> curl http://httpbin.org/post \
>     -H "User-Agent: Mozilla/2.2" \
>     -F param1=hello \
>     -F name=dinsdale \
>     -F name=piranha
> ```

**Comment by decebals** [comment]
If your request is a `multipart/form-data` POST then a call to `request.getParameter()` will always return `null`.
In this case you must use `FileItem`. For an explanation see [this](https://stackoverflow.com/q/15729777).

**Comment by yanvir** [comment]
Thanks for the detail answer, I think I'm having an enlightenment for my problem.

So for processing request `multipart/form-data` I have to do it manually handle it using servlet method? Is there any workaround or snippet that you can share for manage that? Some of my API endpoint need to upload file.

**Comment by decebals** [comment]
For update files in Pippo (via [FileItem](https://github.com/pippo-java/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/FileItem.java)) see [here](https://github.com/pippo-java/matilda/blob/8f5f9f0c2a3d62951acc29ae586f2ccb2f578f29/src/main/java/ro/fortsoft/matilda/web/Routes.java#L143) a code snippet from a real application.

If you need more help please let me know.

**Comment by decebals** [comment]
In the end you can use [Apache Commons FileUpload](https://commons.apache.org/proper/commons-fileupload) 
```java
try {
    HttpServletRequest httpRequest = routeContext.getRequest().getHttpServletRequest(); // retrieve HttpServletRequest from Pippo's request
    List<FileItem> items = new ServletFileUpload(new DiskFileItemFactory()).parseRequest(httpRequest);
    for (FileItem item : items) {
        if (item.isFormField()) {
            // process regular form field (input type="text|radio|checkbox|etc", select, etc).
            String fieldName = item.getFieldName();
            String fieldValue = item.getString();
            // do your job here
        } else {
            // process form file field (input type="file"). you can use also the FileItem from Pippo
            String fieldName = item.getFieldName();
            String fileName = FilenameUtils.getName(item.getName());
            InputStream fileInput = item.getInputStream();
            // do your job here
        }
    }
} catch (FileUploadException e) {
    throw new ServletException("Cannot parse multipart request", e);
}
```

I don't know if we can improve FileItem class from Pippo to eliminate the need for Apache Commons FileUpload when we process for field from a `multipart/form-data` POST.

**Comment by decebals** [comment]
Can we close this issue? Do you need help?

**Comment by yanvir** [comment]
Thanks Decebals, everything work fine, though I have to change the code for fileupload you shared, but everything works fine now, I can receive all parameter passed to the API. Issue closed.
