### ISSUE TITLE
Update Undertow to v2.x.x

### ISSUE THREAD

**Issue by huysamen** [pippo-java/pippo#429]
Undertow 2 has been out for a while now (currently on version 2.0.9.Final) and it would be great to have this in Pippo, as there are numerous improvements, especially around Java 9/10 changes.

**edit**
I have added it via Maven exclusions and have not had any issues so far.

**Comment by decebals** [comment]
@huysamen 
Thanks for this useful information. If you have some free time please submit a PR with this modification.

**Comment by decebals** [comment]
I see that Undertow 2.x is based on Servlet 4 and probably is a problem (Pippo is based on Servlet 3.1).
Maybe an idea is to update to version 1.4.25.Final (now the current version in Pippo is 1.4.12.Final). Undertow 1.4 is based on Servlet 3.1

**Comment by decebals** [comment]
For the moment, with commit 76cc4917e0eeb1598efd39ddd8c9c80f58b0f527, I updated Undertow to 1.4.25.Final (latest 1.4 version).
