### ISSUE TITLE
Add CorsHandler

### ISSUE THREAD

**Issue by mhagnumdw** [pippo-java/pippo#453]
What do you think of adding a handler for CORS? Analogous to the existing CSRFHandler.

I had the need and I made two implementations.

How can I submit them to decide which one to use? (if there is interest)

**Comment by decebals** [comment]
@mhagnumdw 
> What do you think of adding a handler for CORS? Analogous to the existing CSRFHandler.

I think that it's OK. I didn't use this kind of mechanism in last period but I think that could be interesting for other people. In the end a PR is very welcome, even as a model.

Personally, I prefer to start with a basic implementation, something minimalist.
