### ISSUE TITLE
Check if stream is closed

### ISSUE THREAD

**Issue by kiru** [pippo-java/pippo#455]
Hello, 

While debugging, I ended up several times [here](https://github.com/pippo-java/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/gzip/GZipResponseStream.java#L47) which was called by [this](https://github.com/pippo-java/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/util/IoUtils.java#L134). 

We can avoid this by check if the stream is already closed or not. 

Thanks, 
Kiru

**Comment by decebals** [comment]
Sure. Please submit a PR.

**Comment by decebals** [comment]
Closed by #457
