### ISSUE TITLE
How to get the latest version of Tomcat?

### ISSUE THREAD

**Issue by goelanubhav9** [pippo-java/pippo#460]
Hello Team,

**pippo-tomcat.jar  v1.11.0**  currently supports Tomcat version **8.0.33**. Tomcat version 8.0.33 is an obsolete version and no more supported. 
In my project I have a requirement to use **Tomcat 8.5.34**.
How can i update the pippo-tomcat jar / Tomcat so that I can use Tomcat 8.5.34.

Regards
Anubhav Goel

**Comment by decebals** [comment]
You have two variants:
1. submit a patch (PR) with the new Tomcat version (recommended)
2. add an explicit dependency to Tomcat 8.5.34 in your project and `exclude` tomcat dependency from pippo-tomcat.

For the first point (1) what you must to do:
- fork Pippo
![image](https://user-images.githubusercontent.com/1248311/46397974-6f875b00-c6fc-11e8-8a65-6a4e9eb540b7.png)
- clone fork on your local machine (`git clone <fork_repo>`)
![image](https://user-images.githubusercontent.com/1248311/46398007-904fb080-c6fc-11e8-9f6a-85b1c30635c8.png)
- make the modification in [pom.xml](https://github.com/pippo-java/pippo/blob/master/pippo-server-parent/pippo-tomcat/pom.xml#L17) of pippo-tomcat
- install the new version on your computer with (`mvn clean install`)
- test the modification in your app (use pippo 1.11.0-SNAPSHOT version installed in the previous step)
- if the everything is OK in you application, submit a PR with modification
