### ISSUE TITLE
[Question] Gzip With Accept-Encondig:*

### ISSUE THREAD

**Issue by munendrasn** [pippo-java/pippo#473]
When the request has explicit `Accept-Encoding:*`, it would be nice if the gzipped response is sent. With the explicit `*`, it shows that the client is able to handle the gzip response

Also, should Pippo support `qvalue`?? In future, this can be used to support other Encoding. Also, `gzip;q=0` is sent then, gzip response shouldn't be sent .
This is not a problem/issue. As per RFC-7231 
```
Note: Most HTTP/1.0 applications do not recognize or obey qvalues
associated with content-codings.  This means that qvalues might
not work and are not permitted with x-gzip or x-compress.
```

**Comment by decebals** [comment]
@munendrasn 
I don't fully understand the impact of this feature. Do you need or encountered a use case for this?
I found a discussion on [stackoverflow](https://stackoverflow.com/questions/42084137/what-does-accept-encoding-mean) about this subject.

In the end, if the implementation is light and the benefit is clear please come with a PR.

**Comment by munendrasn** [comment]
@decebals  I was also thinking on the similar lines as mentioned in the stackoverflow
```
* As the server, if I receive no Accept-Encoding header I could assume that the client does not even know about content encoding. It is safer to use plain text.
* As the server, if I receive a Accept-Encoding header, that means the client knows about content encoding and it is really willing to accept anything. Well, gzip is a good choice to spare bandwidth, and it is well supported.
```
When there is any explicit `Accept-Encodig` with `*` that means really willing to accept anything. So, sending `gzip` would reduce response size. This would be simple change
```java
!StringUtils.isNullOrEmpty(acceptEncoding) && (
            acceptEncoding.contains("gzip")  || acceptEncoding.contains("*")
        )
```

Regarding `qvalue`, It is mentioned in RFC but haven't seen its usage till now.
