### ISSUE TITLE
UndertowWebSocketConnection uses wrong method to close the socket

### ISSUE THREAD

**Issue by whyicantusemyemailasusername** [pippo-java/pippo#480]
it calls WebSocketChannel.sendClose() which is wrong; javadoc says `Send a Close frame without a payload`. It actually clears up closeReason/closeCode before sending the close frame.
I suppose `WebSockets.sendClose` or `WebSockets.sendCloseBlocking` should be used instead.

**Comment by decebals** [comment]
@whyicantusemyemailasusername 
Can you submit a PR? Thanks!
