### ISSUE TITLE
xxe vulnerabilities

### ISSUE THREAD

**Issue by 360CodeSafe** [pippo-java/pippo#486]
Hello, I am a member of the 360 Code Guard team. In our open source project code audit, we found that Pippo has xxE vulnerabilities. Details are as follows.
 pippo/pippo-content-type-parent/pippo-jaxb/src/main/java/ro/pippo/jaxb/JaxbEngine.java
![default](https://user-images.githubusercontent.com/39950310/49783916-75319a80-fd56-11e8-8d22-4c7816959c51.png)
Because the XML parser does not disable dtd, xxE attacks can occur when content parameters are controlled by malicious attackers

**Comment by decebals** [comment]
@360CodeSafe 
Thanks! Do you have a solution? Can you create a PR?

**Comment by decebals** [comment]
@360CodeSafe 
The information supplied by you is enough for me to fix the problem. Thanks!
