### ISSUE TITLE
Question: How to bind to multiple ports?

### ISSUE THREAD

**Issue by ayltai** [pippo-java/pippo#501]
How to bind to HTTP port 80 and HTTPS port 443 with a single Pippo server instance?

**Comment by decebals** [comment]
I think that is not possible via application's settings.
In [application.properties](https://github.com/pippo-java/pippo-demo/blob/master/pippo-demo-basic/src/main/resources/conf/application.properties) is defined only a single port, something like:
```properties
# Control the port that Pippo binds
server.port = 8338

# SSL configuration
server.keystoreFile = keystore.jks
server.keystorePassword = password
server.truststoreFile = truststore.jks
server.truststorePassword = password
```

In the end you can achieve what you want, creating a custom Jetty server, where you can add an extra one connector, and inject this new server in Pippo.

Take a look for example at [JettyServer](https://github.com/pippo-java/pippo/blob/master/pippo-server-parent/pippo-jetty/src/main/java/ro/pippo/jetty/JettyServer.java). You can override some methods like `createServer` or `createServerConnector`

**Comment by ayltai** [comment]
Thanks @decebals I have been trying to find a nice way to listen to both HTTP and HTTPS ports and share the same handlers. You suggestion seems feasible to me.
