### ISSUE TITLE
How to get servlet 3.1 support with pippo-tjws?

### ISSUE THREAD

**Issue by deepakmn** [pippo-java/pippo#511]
pippo-tjws 1.12.0 downloads servlet-api 2.5 as a dependency. What do I need to do to get servlet 3.1 support with tjws? Besides, when it is mentioned under Server section of docs that Pippo is based on Servlet 3.1 why is servlet 2.5 added as a dependency?

**Comment by decebals** [comment]
> NOTE: TJWS is now deprecated. Consider using the more modern Undertow.

https://docs.jboss.org/resteasy/docs/3.1.4.Final/userguide/html/RESTEasy_Embedded_Container.html.

I tried TJWS in few projects and I encountered some problems (something about request header) which I  have solved. I recommend you to use Undertow.
I propose you to remove TJWS support from the next version pf Pippo (see #504).
