### ISSUE TITLE
Remove pippo-tjws module from next major version of Pippo

### ISSUE THREAD

**Issue by decebals** [pippo-java/pippo#512]
> NOTE: TJWS is now deprecated. Consider using the more modern Undertow.

https://docs.jboss.org/resteasy/docs/3.1.4.Final/userguide/html/RESTEasy_Embedded_Container.html.

Next major version of Pippo will be based on `Servlet 4` (#504). TJWS is based on `Servlet 2` and it's not active maintained.

**Comment by mhagnumdw** [comment]
Hi @decebals , this issue seems to be a good one.

Every time I import Pippo in my Eclipse I have this problem.

![image](https://user-images.githubusercontent.com/17688846/74341517-a193dd00-4d86-11ea-9a9e-04ea6b196ee5.png)

**Comment by mhagnumdw** [comment]
Can I work on this issue?

**Comment by decebals** [comment]
@mhagnumdw Yes,please!
