### ISSUE TITLE
@Param not mapped

### ISSUE THREAD

**Issue by pitschr** [pippo-java/pippo#515]
Hello.

I am struggling with `@Param` annotation and followed the documentation:
http://www.pippo.ro/mod/controller.html

	Controller

    It should accept main as integer (between 0 and 9)

    import ro.pippo.controller.extractor.Param;

    @GET("/project/groups/{main:[0-9]}")
    @Produces(Produces.JSON)
    public List<XmlGroupRange> getMiddleGroups(@Param int main) {
        log.trace("Request for all middle group of main group '{}' in project", main);
        // code
    }

    pom.xml

    <compilerArgs>
        <arg>-Xlint:unchecked</arg>
        <arg>-parameters</arg>
    </compilerArgs>

The JUnit test case is calling '`/api/v1/project/groups/2`' via GET method.

According to the log line I see that the request is accepted - however the `@Param` is not recognized properly for some reasons. 

```
[TEST] [.] 2019-05-23 21:17:06,405 [DEBUG] [ro.pippo.core.PippoFilter:151] - Request GET '/api/v1/project/groups/2'
[TEST] [.] 2019-05-23 21:17:06,407 [TRACE] [ro.pippo.core.route.DefaultRouter:203] - Finding route matches for GET '/api/v1/project/groups/2'
[TEST] [.] 2019-05-23 21:17:06,408 [DEBUG] [ro.pippo.core.route.DefaultRouter:223] - Found 1 route matches for GET '/api/v1/project/groups/2'
[TEST] [.] 2019-05-23 21:17:06,411 [TRACE] [ro.pippo.core.route.DefaultRouteContext:272] - Found Route{requestMethod='GET', uriPattern='/api/v1/project/groups/{main:[0-9]}'}
[TEST] [.] 2019-05-23 21:17:06,413 [TRACE] [ro.pippo.core.route.DefaultRouteContext:278] - Added path parameters to request
[TEST] [.] 2019-05-23 21:17:06,413 [DEBUG] [ro.pippo.core.route.DefaultRouteContext:395] - Executing handler for GET '/api/v1/project/groups/{main:[0-9]}'
[TEST] [.] 2019-05-23 21:17:06,414 [TRACE] [ro.pippo.controller.ControllerHandler:101] - Processing 'li.pitschmann.knx.daemon.v1.controllers.ProjectController::getMiddleGroups' interceptors
[TEST] [.] 2019-05-23 21:17:06,414 [TRACE] [ro.pippo.controller.ControllerHandler:119] - Preparing 'li.pitschmann.knx.daemon.v1.controllers.ProjectController::getMiddleGroups' parameters from request
[TEST] [.] 2019-05-23 21:17:06,415 [TRACE] [ro.pippo.controller.ControllerHandler:122] - Invoking 'li.pitschmann.knx.daemon.v1.controllers.ProjectController::getMiddleGroups'
[TEST] [.] 2019-05-23 21:17:06,576 [TRACE] [l.p.k.d.v1.controllers.ProjectController:176] - Request for all middle group of main group '0' in project
```

I also tried with `@Param("main")` which has same effect and the main group is returned as `0`(expected is `2`)

```
[TEST] [.] 2019-05-23 21:03:27,296 [TRACE] [l.p.k.d.v1.controllers.ProjectController:176] - Request for all middle group of main group '0' in project
```

When changing the type of parameter to `String` then it returns `null`.

```
[TEST] [.] 2019-05-23 21:04:41,374 [TRACE] [l.p.k.d.v1.controllers.ProjectController:176] - Request for all middle group of main group 'null' in project
```

For some reasons the "main" parameter is not mapped; according to the docs it should be the case. Any idea what might be wrong? Do I miss something?

KR, Christoph

**Comment by pitschr** [comment]
I found the root cause ....

I had to change (by adding one space) from
`@GET("/project/groups/{main:[0-9]}")`
to
`@GET("/project/groups/{main: [0-9]}")`

```
[TEST] [.] 2019-05-23 23:46:44,921 [TRACE] [l.p.k.d.v1.controllers.ProjectController:176] - Request for all middle group of main group '2' in project
```

"That's the most evil thing I can imagine" 😆

**Comment by decebals** [comment]
@pitschr 

> I had to change (by adding one space) from ...

If you think that is an issue, please send a PR. Thanks!
