### ISSUE TITLE
CryptoUtils.hmacDigest unsafe with non-ascii inputs

### ISSUE THREAD

**Issue by lambdaupb** [pippo-java/pippo#522]
Java will replace unmapped codepoints with replacement characters like `?` when encoding with a charset that does not contain a code that occurs in the input.

```java
    public static String hmacDigest(String message, String secretKey, String algorithm) {
        String digest = null;
        try {
            SecretKeySpec key = new SecretKeySpec(secretKey.getBytes(StandardCharsets.UTF_8), algorithm);
            Mac mac = Mac.getInstance(algorithm);
            mac.init(key);

            byte[] bytes = mac.doFinal(message.getBytes(StandardCharsets.US_ASCII));

            digest = toHex(bytes);
        } catch (InvalidKeyException e) {
        } catch (NoSuchAlgorithmException e) {
        }
        return digest;
    }
```

Will sign `???` instead of either `äöü` or `äää`. 

Both should be encoded with UTF-8

**Comment by decebals** [comment]
@lambdaupb 
Please create a PR. In the end if you cannot supply a PR I can fix myself the problem (the modification is very simple).

**Comment by lambdaupb** [comment]
If you could do it, I think it would take a lot less time.
