### ISSUE TITLE
Controllers are not being located in subpackages / addControllers

### ISSUE THREAD

**Issue by mhagnumdw** [pippo-java/pippo#530]
Hi!

### Problem
Controllers are not being located in subpackages in some cases.

### Structure
```
.
└── ro
    └── pippo
        └── classpathtest
            ├── controllers
            │   ├── b
            │   │   └── ControllerB.java
            │   └── ControllerA.java
            ├── PippoApplication.java
            └── PippoLauncher.java
```

### PippoApplication
```java
public class PippoApplication extends ControllerApplication {

    @Override
    protected void onInit() {
        // ...
        addControllers("ro.pippo.classpathtest.controllers");
        // ...
    }

}
```

### Cases
- `ControllerA` is always recognized, we have no problem here
- `ControllerB` is only recognized when the application is run by the JAR like this `java -classpath classpathtest-0.0.1-SNAPSHOT.jar ro.pippo.classpathtest.PippoLauncher`
- `ControllerB` is not recognized when the application is started by an IDE, Eclipse for example, or via the command line with `mvn clean compile exec: java`

### Where's the problem?
Here: [ro.pippo.controller.util.ClassUtils.getClasses(String...)](https://github.com/pippo-java/pippo/blob/release-1.12.0/pippo-controller-parent/pippo-controller/src/main/java/ro/pippo/controller/util/ClassUtils.java#L70)

In JAR mode [`if`](https://github.com/pippo-java/pippo/blob/release-1.12.0/pippo-controller-parent/pippo-controller/src/main/java/ro/pippo/controller/util/ClassUtils.java#L77) is executed and in non-JAR mode [`else`](https://github.com/pippo-java/pippo/blob/release-1.12.0/pippo-controller-parent/pippo-controller/src/main/java/ro/pippo/controller/util/ClassUtils.java#L97) is executed, giving a difference in the result of the method.

The size of this method seems strange to me, but I haven't looked at it yet.

### Sample project
https://github.com/mhagnumdw/classpathtest

### Reproduce
```bash
git clone https://github.com/mhagnumdw/classpathtest.git
cd classpathtest/
```

#### Bad things here (IDE version)
```bash
mvn clean compile exec:java
# or via IDE: Eclipse
```
- It works: http://localhost:8338/a
- **Does not work:** http://localhost:8338/b

#### Everything is beautiful here (JAR version)

```bash
mvn clean package
cd target
java -classpath classpathtest-0.0.1-SNAPSHOT.jar ro.pippo.classpathtest.PippoLauncher
```
- It works: http://localhost:8338/a
- And it also works (as expected): http://localhost:8338/b

**Comment by decebals** [comment]
Hi @mhagnumdw 

I am impressed by your issue report. I think that is one of the most complete, clean and beautiful issue report I have ever seen. You put a lot of effort in it. I will take a look to see if I can help.

Recently I started a new project based on Pippp, PF4J, Requery and Spring (only for DI). Until now, in all my projects with Pippo (I have a few) I used the route mechanism from `pippo-core`. I think that for the new project I can switch to controller mechanism form `pippo-controller` to play a little bit with this part of Pippo :smile:.
In the new project, the Pippo code works as expected and from this reason you didn't see activity from my side on this project in the last period of time. Definitely, PIppo is a useful and stable project, and for that I want to thank you all contributors! :medal_military: 
For the new project, I was interested by #513 but in the end I used Pippo's `application.properties` also in Spring and it's fine.

**Comment by mhagnumdw** [comment]
Hi @decebals !!

> I think that for the new project I can switch to controller mechanism form `pippo-controller` to play a little bit with this part of Pippo :smile:.

Do it, it’s very good! :))

> Definitely, PIppo is a useful and stable project, and for that I want to thank you all contributors! :medal_military:

For sure! :100:_%_

**Comment by decebals** [comment]
@mhagnumdw Do you have a solution or a propose for this problem?

**Comment by mhagnumdw** [comment]
Hi @decebals !

I took a look.

> The size of this method seems strange to me, but I haven't looked at it yet.

Now I know why the method is a little long. It really is not such a simple task.

Well... I preferred to make a change to the [ClassUtils.getClasses](https://github.com/pippo-java/pippo/blob/release-1.12.0/pippo-controller-parent/pippo-controller/src/main/java/ro/pippo/controller/util/ClassUtils.java#L70) method. PR coming soon.

Another option would be to use a dependency and I don't think we want to inflate Pippo.

---

Below the result of a research I did.

This [Stackoverflow thread](https://stackoverflow.com/questions/520328/can-you-find-all-classes-in-a-package-using-reflection) can point out several solutions. I will summarize below:

### Guava - ClassPath class
- I believe it’s not an option because we don’t want to make Pippo big unnecessarily
- https://stackoverflow.com/questions/520328/can-you-find-all-classes-in-a-package-using-reflection#13477227
- https://github.com/google/guava/blob/master/guava/src/com/google/common/reflect/ClassPath.java

### org.reflections:reflections
- This is the library I use in my application
- I believe it’s not an option because we don’t want to make Pippo big unnecessarily
- https://stackoverflow.com/questions/520328/can-you-find-all-classes-in-a-package-using-reflection#520339
- https://github.com/ronmamo/reflections

### ClassIndex
- without dependencies
- find classes at compile time
- small, 33 KB
- https://github.com/atteo/classindex
- https://mvnrepository.com/artifact/org.atteo.classindex/classindex/3.9
- https://stackoverflow.com/questions/520328/can-you-find-all-classes-in-a-package-using-reflection#14002663

### Others
- Spring / ClassPathScanningCandidateComponentProvider
- classgraph, seems to be quite robust, https://github.com/classgraph/classgraph
- In the stackoverflow thread mentioned above there are several other approaches without using libs (maybe it works, or not)

**Comment by mhagnumdw** [comment]
Done!
