### ISSUE TITLE
Add ability to configure ContentTypeEngine

### ISSUE THREAD

**Issue by mhagnumdw** [pippo-java/pippo#537]
For example: make it possible to configure GsonEngine, FastjsonEngine etc.

**Comment by decebals** [comment]
After I read again the [documentation](http://www.pippo.ro/doc/content-types.html) I think that it's possible via:
- `application.registerContentTypeEngine(XstreamEngine.class)`
- create an `Initializer`

@mhagnumdw if you have some time please check it. Thanks!

**Comment by mhagnumdw** [comment]
@decebals , this is how I currently do it: `registerContentTypeEngine`.

I didn't even know the [Initializer](https://github.com/pippo-java/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/Initializer.java).  😃 

I was thinking about customizing the engine without having to create a new one. But on second thought now, I think it is not worth the effort as it is very simple to change the engine.

But I have a doubt ...

My engine `MyGsonEngine implements ContentTypeEngine` does not inherit from `GsonEngine` (I currently copy the entire code). Well, if I define the dependency for `pippo-gson` in `pom.xml`, Pippo gives preference to `GsonEngine` and not to my engine. How would it be the best way for me to solve this?

With that I also end up wondering if this log should be INFO or WARN:  [ContentTypeEngines.registerContentTypeEngine](https://github.com/pippo-java/pippo/blob/8333b724e3cd590ea61a69411fae63ee0f196fc9/pippo-core/src/main/java/ro/pippo/core/ContentTypeEngines.java#L102) . What do you think?

**Comment by decebals** [comment]
> With that I also end up wondering if this log should be INFO or WARN: ContentTypeEngines.registerContentTypeEngine . What do you think?

I agree. I think that INFO is more proper.
