### ISSUE TITLE
Make PippoFilter.createApplication protected

### ISSUE THREAD

**Issue by decebals** [pippo-java/pippo#538]
Now, this method is `privat`e and the modification is simple.
The impact is big.
For example, this modification allows me to use a PippoApplication defined as Spring bean in Spring configuration:
```java
public class SpringPippoFilter extends PippoFilter {

    @Override
    protected void createApplication(FilterConfig filterConfig) {
        ServletContext servletContext = filterConfig.getServletContext();
        ApplicationContext applicationContext = WebApplicationContextUtils.getWebApplicationContext(servletContext);
        Application application = (Application) applicationContext.getBean("pippoApplication");
        setApplication(application);
    }

}
```

```java
@Configuration
public SpringConfig {

    @Bean
    public FrontendApplication pippoApplication() {
        return new FrontendApplication();
    }

    // other beans injected via @Autowire in pippoApplication

}
```

```java
@Component
public class FrontendApplication extends Application {

    @Autowired
    private ProductService productService;

    @Override
    protected void onInit() {
        getRouter().ignorePaths("/admin"); // Wicket application

        // send 'Hello World' as response
        GET("/", routeContext -> routeContext.send("Hello World"));

        GET("/products", routeContext -> routeContext.text().send(productService.count()));
    }

}
```

[web.xml]
```xml
    <context-param>
        <param-name>contextClass</param-name>
        <param-value>org.springframework.web.context.support.AnnotationConfigWebApplicationContext</param-value>
    </context-param>

    <context-param>
        <param-name>contextConfigLocation</param-name>
        <param-value>SpringConfig</param-value>
    </context-param>

    <filter>
        <filter-name>pippo.filter</filter-name>
        <filter-class>SpringPippoFilter</filter-class>
    </filter>

```

**Comment by decebals** [comment]
Done in 2b5335c.

**Comment by decebals** [comment]
To add more details to my specific use case, I need to replace the frontend part of a legacy application built with Wicket, with PIppo (both applications built with Pippo and Wicket must coexist and share the same Spring beans).
My usual mode to initiate and start a Pippo application configured with Spring is very simple:
```java
public class Launcher {

    public static void main(String[] args) {
        ApplicationContext context = new AnnotationConfigApplicationContext(SpringConfiguration.class);
        Application application = context.getBean(Application.class);
        Pippo pippo = new Pippo(application);
        pippo.start();
    }

}
```

**Comment by mhagnumdw** [comment]
@decebals, I read your comments.

Could you please explain to me what is the point of joining Pippo with Spring? I would like to understand more about this possible link. Thank you!

**Comment by decebals** [comment]
@mhagnumdw 
Pippo comes already with support builtin for all import DI containers (`Spring`, `Guice` and `CDI`).
The Pippo modules that add support for these DIs (Dependency Injection) are available at https://github.com/pippo-java/pippo/tree/master/pippo-controller-parent (`pippo-spring`, `pippo-guice`, ...). 
We have also a [documentation](http://www.pippo.ro/mod/spring.html) that explains integration with Spring.

Now I see that for example that the integration with Spring is available only if you use controllers.
But, I want to use Spring DI when I use plain routes (instead of controllers) also. And to do that I use the approaches explained in https://github.com/pippo-java/pippo/issues/538#issue-608604498 (if I use `web.xml`) and https://github.com/pippo-java/pippo/issues/538#issuecomment-620849455 (if I use `Pippo` wrapper that comes with pippo-core).
If you need more information, please let me know.
