### ISSUE TITLE
Probable Native memory leak with Java11

### ISSUE THREAD

**Issue by munendrasn** [pippo-java/pippo#541]
Recently, We upgraded one of our service to Java11. We are running the service in Kubernetes. After this upgrade, we started facing restarts because of Kernel OOMKiller.
On debugging, We found Deflator was taking much of the off-heap memory.
All calls to our service have `Accept-Encoding` set to `gzip`. When we looked into GzipResponseStream, we observed GzipOutputStream(this uses Deflater which allocates native memory) is never closed

https://github.com/pippo-java/pippo/blob/a6ab828f9b86c3d6d6737bcb1cd8d1c9d08c9b78/pippo-core/src/main/java/ro/pippo/core/gzip/GZipResponseStream.java#L45

Not closing GzipOutputStream has lead to native memory in other libraries too - https://issues.apache.org/jira/browse/CURATOR-354

@decebals Is there any reason why `close()` in GzipResponseStream doesn't call `GzipOutputStream`'s close()?

**Comment by decebals** [comment]
> Is there any reason why close() in GzipResponseStream doesn't call GzipOutputStream's close()?

I don't remember to have a specific need on this subject. I will take a look in history and I will come with news.
I'm sorry you're in trouble because of Pippo.

**Comment by munendrasn** [comment]
@decebals 
Thanks for looking into it. Sharing a few other things we checked before raising the issue
*  git-history for GzipResponseStream, it always used `finish()`. Didn't check the repo before the commit (to rule out it is moved from different pippo-package so history might be lost)

>I'm sorry you're in trouble because of Pippo.

Bugs can arise but we love Pippo and use it in all our services written in Java.

**Comment by decebals** [comment]
My conclusion is that probable I wanted to reuse `GZIPOutputStream`. And from this reason I call only [GZIPOutputStream.finsh](https://docs.oracle.com/javase/8/docs/api/java/util/zip/GZIPOutputStream.html#finish--) method. I see in javadoc of `finish` method:
> Finishes writing compressed data to the output stream without closing the underlying stream. Use this method when applying multiple filters in succession to the same output stream.

That class (GZipResponseStream) was introduced by https://github.com/pippo-java/pippo/issues/331.

@munendrasn Do you see any solution?

**Comment by munendrasn** [comment]
Fastest and straightforward approach would be to do close call. Other which I have seen in Apache-curator is to maintain a pool of deflators since that is real cost. https://github.com/apache/curator/pull/282
Similar approach maybe in Jetty too
Were your planned reuse meant to maintain a pool of gzipoutputstream?

**Comment by munendrasn** [comment]
Currently, GzipOutputStream(unlike DeflatorOutputStream) doesn't take deflator as an arg in any constructor. Hence, I have raised PR #542 which closes the stream. This would memory leak and then we could build on top of this if reusability needs to be supported

**Comment by munendrasn** [comment]
@decebals 
It is been ~18 months from the last [release](https://github.com/pippo-java/pippo/releases/tag/release-1.12.0). Can we plan for a release?

**Comment by decebals** [comment]
@munendrasn 
> Can we plan for a release?

I asked the same question in this morning on Gitter:
![image](https://user-images.githubusercontent.com/1248311/83117742-20164f80-a0d6-11ea-8b80-bce33ba1d89e.png)

Sure, I am available to release a new version if everything is ready.

**Comment by munendrasn** [comment]
I think we are good for a release. The release would contain some important fixes and improvements
* FileItem extraction
* Fix for Controller package
* Fix for memory leak
* Fix for content-length issue

Apart from the above, we have some dependency upgrades
