### ISSUE TITLE
Error after I upgraded from 1.12.0 to 1.13.0

### ISSUE THREAD

**Issue by decebals** [pippo-java/pippo#545]
After I upgraded from 1.12.0 (more precisely from `1.13.0-SNAPSHOT`) to the new released `1.13.0` my application based on bootstrap (webjars) doesn't look good (the "goodies" introduced by bootstrap is not available and the pages look as plain html).
![image](https://user-images.githubusercontent.com/1248311/83348371-94e6c500-a334-11ea-81a5-4ee03ece4e1d.png)
In the browser's console I see some errors (jquery is not available):
![image](https://user-images.githubusercontent.com/1248311/83348389-d6777000-a334-11ea-816d-70ab25f8f3ec.png)

With an old `1.13.0-SNAPSHOT` worked as expected so the problem is introduced by latest commits.

**Comment by decebals** [comment]
![image](https://user-images.githubusercontent.com/1248311/83348450-73d2a400-a335-11ea-9a93-d6e289cc96d3.png)

**Comment by decebals** [comment]
After some investigation I realized that the webjars's js are empty
![image](https://user-images.githubusercontent.com/1248311/83348632-27886380-a337-11ea-9793-2dd59520ee42.png)

**Comment by decebals** [comment]
The same problem for css
![image](https://user-images.githubusercontent.com/1248311/83348716-a54c6f00-a337-11ea-98d9-d52a00df9bdb.png)

**Comment by mhagnumdw** [comment]
Hi @decebals !

The problem is actually in the commit https://github.com/pippo-java/pippo/commit/3cebb2caf7d12012b500f3e2896006f39ad5cf0f

Unfortunately I can't look at it right now.

For now, you can revert this commit and release patch version 1.14.1.

**Comment by decebals** [comment]
@mhagnumdw Thanks for your support.
Now, the problem is solved and I released a new version (`1.13.1`).

**Comment by mhagnumdw** [comment]
You're welcome!

@decebals , what do you think of removing the 1.13.0 release? Both from GitHub and the maven repository.

**Comment by decebals** [comment]
> what do you think of removing the 1.13.0 release? Both from GitHub and the maven repository.

I don't think it is necessary. 13 is an unlucky number :smile:.
