### ISSUE TITLE
Make some methods public in the PippoRule class

### ISSUE THREAD

**Issue by mhagnumdw** [pippo-java/pippo#547]
Hi!

I would like to make the methods below public. Everything ok for you?
- startPippo
- stopPippo

I would also like to take advantage of the moment and remove the input parameter, since it is set via the constructor.

**Comment by decebals** [comment]
@mhagnumdw 
Sorry for delay. I am OK to make that methods public but to be honest I don't understand your use case and how these modifications help you.

**Comment by mhagnumdw** [comment]
I am creating a JUnit Runner for some tests of my application. In some cases, at the boot of my runner, I use `PippoRule` (create an instance) to take advantage of the start and stop logic it has.

Another scenario is that the annotation `@ClassRule` is not supported by `@RunWith(PowerMockRunner.class)`, it being necessary to start and stop Pippo in the methods annotated with `@BeforeClass` and `@AfterClass` and for that it is necessary to have access to some methods of the `PippoRule` class.

For now I created a class that inherits from `PippoRule` to do this.

**Comment by decebals** [comment]
@mhagnumdw Thanks for explanations. I asked you because I love to see how other people use Pippo. There is a lot of room for improvement.
As I said, for me the modifications are OK.

**Comment by mhagnumdw** [comment]
@decebals 
And I like to answer! :)
