### ISSUE TITLE
Improving ClassUtils

### ISSUE THREAD

**Issue by mhagnumdw** [pippo-java/pippo#560]
Hi!

Issue #530 fixed it well! But I ended up getting a problem with the automated testing of my application.

It all starts with calling the `addControllers("my.domain.controller")` method in `Application.onInit()`...

I have controllers in the `my.domain.controller` package in the `src/main/java` folder and I have tests of these controllers in the same package in the `src/test/java` folder.

The [getResources("my/domain/controller")](https://github.com/pippo-java/pippo/blob/efdf87edf0186dc85c80c9dbd30e1d20c2100cb2/pippo-controller-parent/pippo-controller/src/main/java/ro/pippo/controller/util/ClassUtils.java#L76) method returns the two paths above (`main` and `test`). Although at this point I don't want the test classes, but I think that's ok so far, I don't see it as a problem.

Later on, the [getClass(String className)](https://github.com/pippo-java/pippo/blob/efdf87edf0186dc85c80c9dbd30e1d20c2100cb2/pippo-controller-parent/pippo-controller/src/main/java/ro/pippo/controller/util/ClassUtils.java#L57) method ends up throwing the `java.lang.ExceptionInInitializerError`. In my case here, the problem occurs because a test class of mine has the code below

```java
@ClassRule
public static LoginRule sessionAdmin = new LoginRule("admin").login();
```

and the [Class.forName](https://github.com/pippo-java/pippo/blob/efdf87edf0186dc85c80c9dbd30e1d20c2100cb2/pippo-controller-parent/pippo-controller/src/main/java/ro/pippo/controller/util/ClassUtils.java#L59) method, by default, ends up instantiating everything that is static in the class. And at the time of the application boot, when we use for example the method `addControllers("my.domain.controller")`, it doesn't make much sense the static content is being initialized at that moment.

What I have already tested and solved - and I think it makes sense given the purpose of the `ClassUtils` class - is to change the line below, of the method `getClass`, from

```java
return (Class<T>) Class.forName(className);
```

to

```java
return (Class<T>) Class.forName(className, false, ClassUtils.class.getClassLoader());
```

Or even create another method in `ClassUtils`, which I think is better, with the signature

```java
public static <T> Class<T> getClass(String className, boolean initialize) {
```

What do you think?

_ps: Sorry to be long, but it was the best way I found to explain well why the proposed change._

**Comment by decebals** [comment]
@mhagnumdw Please propose a MR with a solution that solves the problem and which you prefer the most.

**Comment by mhagnumdw** [comment]
I could no longer reproduce this problem. Closing the issue now.
