### ISSUE TITLE
[Question] Thread-safety of WebSocketContext?

### ISSUE THREAD

**Issue by midn1** [pippo-java/pippo#577]
Is it safe to call `WebSocketContext::sendMessage` from background threads?

**Comment by midn1** [comment]
It seems from my research that this is a no.

**Comment by decebals** [comment]
@midn1 Your observation is good. We are waiting for you with other questions.

**Comment by midn1** [comment]
What about writing? It seems that Jetty's `sendMessage` is thread-safe.
