### ISSUE TITLE
Implementing two buttons in a single form

### ISSUE THREAD

**Issue by mind-overflow** [pippo-java/pippo#584]
Unfortunately, I tried looking at the examples but I was unable to find anything similar to this.
As specified by [the official documentation](http://www.pippo.ro/doc/forms.html), you can send data to the server (eg. via POST) from a web form by adding something like this in the template file:  
```html
<form accept-charset="UTF-8" role="form" method="post" action="/login">
        <input placeholder="Username" name="username">
        <input placeholder="Password" name="password" type="password">
        <input class="btn btn-success btn-block" type="submit" value="Login">
</form>
```  
  
And then, by adding a POST handler in your Java Application:
```java
POST("/login", routeContext -> {
    
    String name = routeContext.getParameter("username").toString();
    System.out.println(name);

    String password = routeContext.getParameter("password").toString();
    System.out.println(password);

});
```  
  
However, I can't find any way to recognize two different buttons (eg. "login" and "register").
I can differentiate them in HTML by adding a `name="loginbtn"` to the `<input>` element, but then, I have no way to recognize the element's name in Java.
```html
<input class="btn btn-success btn-block" type="submit" name="loginbtn" value="Login">
```
  
If I have to make a comparison, in Spring you can simply add a `param="loginbtn"` value and the handler will automatically detect it:
```java
@RequestMapping(value = "/login", method = RequestMethod.POST, params = "loginbtn")
public String submit(...) {
  <...>
}
```  
  
However, I can't seem to be able to do this with Pippo.  
I'm sure I'm just probably missing something. Can anyone help me? Thanks!

**Comment by mind-overflow** [comment]
Update: I think I found a way, but I'm pretty sure it's not the proper one.
Instead of using an Application, I use a ControllerApplication and, in the controller, I do this:
```java
    @POST("login")
    public void handleLogin(@Param("loginbtn") String loginbtn, @Param("registerbtn") String registerbtn)
    {
        if(loginbtn != null)
        {
            <...handle login...>
        }
        else if(registerbtn != null)
        {
            <...handle registration...>
        }
    }
```
  
If anyone knows of a better way to implement this, please share it - thank you!

**Comment by decebals** [comment]
@mind-overflow I have not encountered this use case in my projects. Your approach is good.
Probably, in your case, I will try to use the newer HTML5 solution using `formaction` attribute and to have two different end points (routes) in my application.

**Comment by decebals** [comment]
@mind-overflow Can we close this issue?

**Comment by mind-overflow** [comment]
yes of course! sorry for not replying. thanks for the suggestion and I'm glad it was a good approach!
