### ISSUE TITLE
Out of heap space for larger file uploads

### ISSUE THREAD

**Issue by dunsunik** [pippo-java/pippo#586]
Hello,

I experience such an error while trying to write my uploads (20MB file) onto a disk.
 
FileItem file = cx.getRequest().getFile("file");
file.write(new File('/tmp/myfile.jpg'));

Looking at pippo framework source code write method calls IoUtils.copy method. And that one uses a buffered read approach. 
So obviously it should not be a problem, right ?
So why does it eat my heap space memory ?

Thank you

**Comment by decebals** [comment]
@dunsunik 
Can you add information about which Java version are you use and what is the (max) heap size of your app?

**Comment by dunsunik** [comment]
Yes sure.
I use Java 17 and compiling it to v16 compatibility.
My heap size is set to very low (16MB) values since it is run in a restricted environment I use all the tricks I can to get memory consumption as low as possible (disabled JIT and other stuff). 
Anyways even if I raise Xss to 32MB it's not enough (for 8MB file upload), which looks like it reads (the whole file) into the memory.

Any thoughts ?

**Comment by decebals** [comment]
I understand your problem.
What servlet engine are you use (tomcat, jetty, undertow)? 
Can you create a simple [quickstart](http://www.pippo.ro/dev/quickstart.html) application that replicate the problem and to make it public (on ghithub or a git repository in genera, or attach the project zip here)? The idea is to be able to reproduce and debug the problem is isolation.

**Comment by decebals** [comment]
I will try to investigate the problem using [pippo-demo-upload](https://github.com/pippo-java/pippo-demo/tree/master/pippo-demo-upload).

**Comment by dunsunik** [comment]
I was on the go so was a bit in hurry.

I use these java flags when starting my cloud apps:
-Xms16M  -Xmx32M -Xss512k  -Xint  -Xshare:off -XX:+UseSerialGC

I use jetty. And there is really nothing special about my app. It's practically a blank pippo app (I just wanted to test drive file uploads now). I use multipart file upload.

@Path("/admin")
@AdminRoleRequired
public class AdminCtrl extends BaseCtrl {

	@POST("/upload-photos")
	@Named("uploadPhotosPost")
	@Produces(Produces.JSON)
	public String uploadPhotosPost() {

		FileItem file = cx.getRequest().getFile("file");

		java.nio.file.Path path = java.nio.file.Path.of(conf.getString("app.gallery.dir.upload", ""),
				file.getSubmittedFileName());

		try {
			file.write(path.toFile());
		} catch (IOException e) {
			e.printStackTrace();
			log.error(e.getMessage());
		}

		return "OK";
	}
}

**Comment by decebals** [comment]
> I will try to investigate the problem using [pippo-demo-upload](https://github.com/pippo-java/pippo-demo/tree/master/pippo-demo-upload).

I tested using Java flags and the file size supplied by you.
My conclusion is the problem is only in Jetty, on Tomcat and Undertow everything works as expected.
On Jetty the stacktrace looks like:
```
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:135)
	at org.eclipse.jetty.util.MultiPartInputStreamParser$MultiPart.write(MultiPartInputStreamParser.java:173)
	at org.eclipse.jetty.util.MultiPartInputStreamParser.parse(MultiPartInputStreamParser.java:797)
	at org.eclipse.jetty.util.MultiPartInputStreamParser.getParts(MultiPartInputStreamParser.java:482)
	at org.eclipse.jetty.server.MultiParts$MultiPartsUtilParser.getParts(MultiParts.java:112)
	at org.eclipse.jetty.server.Request.getParts(Request.java:2326)
	at org.eclipse.jetty.server.Request.extractContentParameters(Request.java:529)
	at org.eclipse.jetty.server.Request.getParameters(Request.java:430)
	at org.eclipse.jetty.server.Request.getParameterNames(Request.java:1077)
	at ro.pippo.core.Request.initParameters(Request.java:145)
	at ro.pippo.core.Request.<init>(Request.java:79)
	at ro.pippo.core.RequestResponseFactory.createRequestResponse(RequestResponseFactory.java:36)
	at ro.pippo.core.PippoFilter.doFilter(PippoFilter.java:130)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at ro.pippo.jetty.JettyServer$PippoHandler.doHandle(JettyServer.java:264)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
```

My advice for you is to switch from Jetty to Undertow (my recommendation) or Tomcat. Just replace `pippo-jetty` with `pippo-undetow` or `pippo-tomcat` as dependency and that is all.

**Comment by mhagnumdw** [comment]
@dunsunik , try with the latest version of Jetty for java8: https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-servlet

**Comment by mhagnumdw** [comment]
@decebals  , can you remind me how to override the `JettyServer` class so I can run some tests related to this issue?

**Comment by mhagnumdw** [comment]
> @dunsunik , try with the latest version of Jetty for java8: https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-servlet
> 
> Jetty versions: https://www.eclipse.org/jetty/

Tested. Unsuccessfully.

**Comment by decebals** [comment]
> @decebals , can you remind me how to override the `JettyServer` class so I can run some tests related to this issue?

Please see http://www.pippo.ro/doc/server.html. In some situation when I want to test a very deeply aspect of the (Jetty) server, I modify the `pippo-jetty` module, I do an install on my local machine, and I force the test application to use the local version.

**Comment by mhagnumdw** [comment]
@dunsunik , the solution if you want to use Jetty:

Create a custom `JettyServer`:

```java
import javax.servlet.MultipartConfigElement;

import ro.pippo.core.Application;
import ro.pippo.jetty.JettyServer;

public class MyJettyServer extends JettyServer {

    @Override
    protected MultipartConfigElement createMultipartConfigElement() {
        System.out.println("Hi! I'm here! - createMultipartConfigElement");
        Application application = getApplication();
        String location = application.getUploadLocation();
        long maxFileSize = application.getMaximumUploadSize();
        
        // Gets the size threshold after which files will be written to disk.
        // see: javax.servlet.MultipartConfigElement.getFileSizeThreshold()
        int fileSizeThreshold = 1 * 1024 * 1024; // 1 MB
        
        return new MultipartConfigElement(location, maxFileSize, -1L, fileSizeThreshold);
    }

}
```

**The `fileSizeThreshold` parameter does the magic.** It tells how many bytes of the file the server must keep in memory before overflowing to disk. By default it is 0, as can be seen [here](https://github.com/pippo-java/pippo/blob/e4a22bada5cd6961ec7de9ca2d5979cf58a556f4/pippo-core/src/main/java/ro/pippo/core/AbstractWebServer.java#L131). Apparently, if 0, Jetty puts the entire file into memory.

Note that in the example above I set it to 1MB.

Now you need to tell Pippo to use this server, something like:

```java
public class UploadDemo {

    public static void main(String[] args) {
        Pippo pippo = new Pippo(new UploadApplication());
        pippo.setServer(new MyJettyServer()); // my custom jetty server
        pippo.start();
    }

}
```

And now, with the jvm parameters you informed (-Xms16M -Xmx32M -Xss512k -Xint -Xshare:off -XX:+UseSerialGC) I managed to upload 20MB and 100MB.

jvisualvm
![visualvm](https://user-images.githubusercontent.com/17688846/142199813-3a9fc77b-ea20-40fe-a1f8-b35694504c55.png)

app
![image](https://user-images.githubusercontent.com/17688846/142199649-8f4b63ca-b58e-429c-b032-6305fb7dce1f.png)

Generate 20MB and 100MB files
- truncate -s 100M ~/temp100m.tmp
- truncate -s 20M ~/temp20m.tmp

FYI: @decebals

**Comment by dunsunik** [comment]
@mhagnumdw Hey, big thanks to you. What a stunning help from you !
By the way I think this fix should be part of a main branch since loading the whole upload content into the memory is kinda well not nice :)

Thanks and Cheers guys !

**Comment by decebals** [comment]
@mhagnumdw Good job!
As @dunsunik said, I think that is a good idea to have this protection by default.
I propose you to create new settings in [WebServerSettings](https://github.com/pippo-java/pippo/blob/e4a22bada5cd6961ec7de9ca2d5979cf58a556f4/pippo-core/src/main/java/ro/pippo/core/WebServerSettings.java):
- `upload.maxFileSize`
- `upload.location`
- `upload.fileSizeThreshold`

and to use these properties in [AbstractWebServer::createMultipartConfigElement](https://github.com/pippo-java/pippo/blob/e4a22bada5cd6961ec7de9ca2d5979cf58a556f4/pippo-core/src/main/java/ro/pippo/core/AbstractWebServer.java#L126). In this mode, we solved the problem in a generic mode (for each supported embedded server)

@mhagnumdw Can you create a MR please?

**Comment by mhagnumdw** [comment]
@decebals , I'll see this.

But remembering that inside `Application` there is [uploadLocation](https://github.com/pippo-java/pippo/blob/e4a22bada5cd6961ec7de9ca2d5979cf58a556f4/pippo-core/src/main/java/ro/pippo/core/Application.java#L69) and [maximumUploadSize](https://github.com/pippo-java/pippo/blob/e4a22bada5cd6961ec7de9ca2d5979cf58a556f4/pippo-core/src/main/java/ro/pippo/core/Application.java#L70).
