### ISSUE TITLE
New release very soon

### ISSUE THREAD

**Issue by decebals** [pippo-java/pippo#587]
I intend to make a new release very soon. I updated already the changelog file with what will contain the release.
Am I miss something? Do you want to see something special in the new release?

**Comment by mhagnumdw** [comment]
I haven't used Pippo in new projects for a while, but I really like Pippo!

At the moment I can't remember anything significant at the moment. Would have to look...

Perhaps this issue can be included in this release. I think it prevented me from advancing the Pippo version in my application: https://github.com/pippo-java/pippo/issues/560
