### ISSUE TITLE
Add Pippo to the TechEmpower Benchmark

### ISSUE THREAD

**Issue by gkresic** [pippo-java/pippo#628]
I would like to see Pippo added to the TechEmpower Benchmark. I think this would get more users and I'm also curious how Pippo compares to the other frameworks.

_Originally posted by @rygel in https://github.com/pippo-java/pippo/issues/409#issuecomment-376302095_

**Comment by decebals** [comment]
I remember about this subject.
See also https://github.com/TechEmpower/FrameworkBenchmarks/pull/2244.

**Comment by gkresic** [comment]
Merged into upstream.

First benchmarks should be available around March 02. at https://tfb-status.techempower.com/

**Comment by gkresic** [comment]
First round of benchmarks with Pippo is completed, Pippo ended up on 62. place:

https://www.techempower.com/benchmarks/#section=test&runid=ef7991e0-35e3-4de1-94b6-1ac13e29b9c6&test=composite
